# Generated by Django 3.0.2 on 2020-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_date', models.IntegerField(max_length=4)),
                ('geo', models.CharField(max_length=30)),
                ('dguid', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('age_group', models.CharField(max_length=10)),
                ('student_response', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=10)),
                ('uom_id', models.IntegerField(max_length=8)),
                ('scalar_factor', models.CharField(max_length=10)),
                ('scalar_id', models.IntegerField(max_length=8)),
                ('vector', models.CharField(max_length=10)),
                ('coordinate', models.CharField(max_length=10)),
                ('value', models.IntegerField(max_length=8)),
                ('status', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('terminated', models.CharField(max_length=10)),
                ('decimals', models.IntegerField(max_length=10)),
            ],
        ),
    ]
