# Generated by Django 3.0.2 on 2020-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_example', '0004_auto_20200304_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='dguid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='terminated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
