# Generated by Django 3.0.2 on 2020-03-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_example', '0003_auto_20200304_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='dguid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='terminated',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='uom',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='uom_id',
            field=models.IntegerField(null=True),
        ),
    ]
